// export const DOMAIN = 'http://ai.devex.yqxiu.cn/service'
export const DOMAIN = 'http://ai.devexp.cn/service'
export const CDNTOKEN = DOMAIN + '/cdn/token'
export const CDNFILENAME = DOMAIN + '/cdn/upload'
export const CDNPREFILENAME = DOMAIN + '/prediction/result'